# Generated by Django 5.2.11 on 2026-02-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_event_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_event_place.eventplace')),
                ('temp', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
